"""add_raw_key_to_api_keys

Revision ID: 4a25eb3cc474
Revises: 8b7846a02c03
Create Date: 2026-05-12 08:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy import Column, Text

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a25eb3cc474"
down_revision = "add_installed_col"
branch_labels = None
depends_on = None


def has_column(table_name, column_name):
    """检查表是否已存在指定列"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table(table_name):
        return False
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not has_column("API_KEYS", "RAW_KEY"):
        op.add_column("API_KEYS", Column("RAW_KEY", Text, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if has_column("API_KEYS", "RAW_KEY"):
        op.drop_column("API_KEYS", "RAW_KEY")
    # ### end Alembic commands ###
