"""1.3.3

Revision ID: 8b7846a02c03
Revises: 6766a9cd1d4b
Create Date: 2026-04-24 17:50:00.000000

"""

import sqlalchemy as sa
from sqlalchemy import Column

from alembic import op

# revision identifiers, used by Alembic.
revision = "8b7846a02c03"
down_revision = "6766a9cd1d4b"
branch_labels = None
depends_on = None


def has_column(table_name, column_name):
    """检查表是否已存在指定列"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table(table_name):
        return False
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # RBAC_MENUS 扩展字段（Vben Admin 路由元数据）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table("RBAC_MENUS"):
        return
    new_columns = [
        ("REDIRECT", sa.String(512), True),
        ("KEEP_ALIVE", sa.Integer, False),
        ("AFFIX_TAB", sa.Integer, False),
        ("HIDE_IN_MENU", sa.Integer, False),
        ("HIDE_IN_TAB", sa.Integer, False),
        ("HIDE_IN_BREADCRUMB", sa.Integer, False),
        ("ACTIVE_ICON", sa.String(512), True),
        ("BADGE", sa.String(64), True),
        ("BADGE_TYPE", sa.String(32), True),
    ]
    for col_name, col_type, nullable in new_columns:
        if not has_column("RBAC_MENUS", col_name):
            if nullable:
                op.add_column("RBAC_MENUS", Column(col_name, col_type, nullable=True))
            else:
                op.add_column("RBAC_MENUS", Column(col_name, col_type, nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for col_name in [
        "REDIRECT",
        "KEEP_ALIVE",
        "AFFIX_TAB",
        "HIDE_IN_MENU",
        "HIDE_IN_TAB",
        "HIDE_IN_BREADCRUMB",
        "ACTIVE_ICON",
        "BADGE",
        "BADGE_TYPE",
    ]:
        if has_column("RBAC_MENUS", col_name):
            op.drop_column("RBAC_MENUS", col_name)
    # ### end Alembic commands ###
