"""1.3.1

Revision ID: a933386acbad
Revises: 9054013d8038
Create Date: 2026-03-15 16:46:35.654189

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a933386acbad"
down_revision = "9054013d8038"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table("MESSAGE_CLIENT"):
        return
    columns = [col["name"] for col in inspector.get_columns("MESSAGE_CLIENT")]
    if "TEMPLATES" not in columns:
        op.add_column("MESSAGE_CLIENT", sa.Column("TEMPLATES", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("MESSAGE_CLIENT", "TEMPLATES")
    # ### end Alembic commands ###
